channels:
- conda-forge
dependencies:
- python=3.10.6
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.1
  - astunparse==1.6.3
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - ipython==8.7.0
  - opt-einsum==3.3.0
  - psutil==5.9.4
  - torch==1.13.1
name: mlflow-env
